### ISSUE TITLE
It seems that transition preview window for 2D skeletal animation is not working

### ISSUE THREAD

**Issue by superkerokero** [KybernetikGames/animancer#182]
# Environment

- Animancer Version Number: 7.2
- Animancer Pro or Lite: Pro
- Unity Version: 2021.2.8f1
- Platform: MacOS

# Description

The clip transition of Animancer provides  [preview accessed from an eye-like button](https://kybernetik.com.au/animancer/docs/manual/transitions/previews/).
When setting the 2d skeletal animation clips created using Unity's  [2D Animation package](https://docs.unity3d.com/Packages/com.unity.2d.animation@7.0/manual/index.html) as [clipTransition](https://kybernetik.com.au/animancer/api/Animancer/ClipTransition/)'s clip, the preview does not update the 2d characters.

The position and rotation of the bones registered within the animation clip does update, but the sprite skin and corresponding Gizmos does not. Forcing the 2D animation system to update during preview should solve the problem.

# Reproduction

Steps to reproduce the bug:

1. Create a 2D skeletal character and create a simple animation clip along with an animator for it.
2. Attach an Animator, an AnimacerComponent and a simple MonoBehaviour exposing a clipTransition to the character created at step 1.
3. Assign the animation clip to clipTransition's clip
4. Try to preview the animation

**Comment by KybernetikGames** [comment]
I've never used the 2D Animation package so would you mind attaching your character and animation clip for me to test (or email it to animancer@kybernetik.com.au)?

Also:

- Does the animation play properly in Play Mode?
- In the Preview Window, does it not work when you click Play Transition or when you click in the event timeline to set the preview time or both?

**Comment by superkerokero** [comment]
@KybernetikGames 

Thanks for the quick response!
I have sent a sample project to you via email.

For additional questions:
- The animation does play properly in Play Mode
- Neither the "Play Transition" button nor the event timeline works in Preview Window

**Comment by KybernetikGames** [comment]
Looks like the code that disables custom components on preview objects to prevent them from executing unexpectedly is breaking the `SpriteSkin` components.

To fix it, find the `DisableUnnecessaryComponents` method in the `TransitionPreviewWindow.Scene` class and replace it with this:

```
private static void DisableUnnecessaryComponents(GameObject root)
{
    var behaviours = root.GetComponentsInChildren<Behaviour>();
    for (int i = 0; i < behaviours.Length; i++)
    {
        var behaviour = behaviours[i];

        // Other undesirable components aren't Behaviours anyway: Transform, MeshFilter, Renderer
        if (behaviour is Animator)
            continue;

        var type = behaviour.GetType();
        if (type.IsDefined(typeof(ExecuteAlways), true) ||
            type.IsDefined(typeof(ExecuteInEditMode), true))
            continue;

        behaviour.enabled = false;
        behaviour.hideFlags |= HideFlags.NotEditable;
    }
}
```

Also, I'm using an earlier version of Unity 2021.2 than you and it gives me this warning whenever I open the preview window:

*SceneView rotation is fixed to identity when in 2D mode. This will be an error in future versions of Unity.*

Do you get the same warning? I'm hoping it's something they patched because the stack trace is useless and removing the code where I rotate the camera doesn't fix it.

**Comment by superkerokero** [comment]
Thanks for the tip. The fix works perfectly!

> SceneView rotation is fixed to identity when in 2D mode. This will be an error in future versions of Unity.

Unfortunately, this error does appear when using 2021.2.7f1 or 2027.2.8f1 too...

**Comment by superkerokero** [comment]
@KybernetikGames 

I just found that although the fix on `DisableUnnecessaryComponents` makes normal bone-based animations work,  IK([the one comes with the unity 2d animation package](https://docs.unity3d.com/Packages/com.unity.2d.animation@5.0/manual/2DIK.html).) still doesn't update actual bones in preview window. IK gizmos aren't updating either.

I have sent an updated sample project with Ik to your email, could you have a look at the IK part as well?

**Comment by KybernetikGames** [comment]
> Turning off the 2D mode in the scene view does not give this warning

So I need to disable 2D Mode in the regular scene view to avoid a warning about rotating the camera in a different scene view where I'm not actually rotating the camera. Well it's dumb but at least it gets rid of the warning. Thanks for checking.

I'm not really sure what's wrong with the IK. Even if I make `DisableUnnecessaryComponents` do nothing so the IK component stays enabled, it still doesn't work.

Note that to control the IK component of the preview, you need to select the preview window's copy of the character using the Settings tab (and make `DisableUnnecessaryComponents` do nothing so it doesn't disable that component's Inspector):
![image](https://user-images.githubusercontent.com/43698611/150097309-9a00cb43-8637-46a0-9fdc-077a0dac269b.png)
But even then the IK still does nothing.

**Comment by superkerokero** [comment]
After some digging into the source code of Unity's [2D Animation](https://docs.unity3d.com/Packages/com.unity.2d.animation@7.0/manual/index.html), I figured out why IK doesn't work in preview window:

Basically, the way 2D IK updates the solvers and gizmos is through registering callbacks to [`SceneView`](https://docs.unity3d.com/ScriptReference/SceneView.html):

```c#
        // The method implemented in "com.unity.2d.animation@7.0.3/IK/Editor/IKEditorManager.cs"
        private void RegisterCallbacks()
        {
            EditorApplication.hierarchyChanged += Initialize;
            Undo.postprocessModifications += OnPostProcessModifications;
            EditorApplication.update += OnLateUpdate;
#if UNITY_2019_1_OR_NEWER
            SceneView.duringSceneGui += OnSceneGUI;
#else
            SceneView.onSceneGUIDelegate += OnSceneGUI;
#endif
            Selection.selectionChanged += OnSelectionChanged;
        }
```

Since Animancer's preview scene is a temporary scene that is newly created, all the neccessary callbacks aren't triggered.

<BR><BR><BR>
***

**To make the IK work in preview window, you need:**

1. Collect references to `UnityEngine.U2D.IK.IKManager2D` during the initialization of the preview scene.
 
```c#
// ( inside `Animancer.Editor.TransitionPreviewWindow`) saved references for later use
public UnityEngine.U2D.IK.IKManager2D[] iKManager2Ds { get; private set; }

// ( inside `Animancer.Editor.TransitionPreviewWindow.InstantiateModel()`) get references from instance root
iKManager2Ds = InstanceRoot.GetComponentsInChildren<UnityEngine.U2D.IK.IKManager2D>();
```

2. Force update 2d solvers in the preview scene.

```c#
// ( inside `Animancer.Editor.TransitionPreviewWindow.Inspector.DoTransitionGUI()`) force update somewhere
foreach (var manager in InstanceScene.iKManager2Ds)
{
    foreach (var solver in manager.solvers)
    {
        solver.UpdateIK(manager.weight);
    }
}
```

3. Since the added code references namespace `UnityEngine.U2D.IK` that is inside a separate assembly, a reference to it is necessary for Animancer's asmdef:

![image](https://user-images.githubusercontent.com/8372499/150151234-edbe36ec-4282-43d7-afc3-1b9d0a0eafa1.png)

***
So with some dirty fix, IK now works in the preview window. But the IK Gizmos still don't work.

Since most of Gizmo related functions are either implemented inside internal classes and/or as private methods, manual update of Gizmos is possible, but extremely tedious with a lot of c# reflection mess. 

***
At least the preview of IK can work with some extra effort, the current status is good enough for practical use.
Hope the information I put here helps someone else that tries to use Animancer with Unity's 2D Animation package.

**Comment by KybernetikGames** [comment]
Events like `SceneView.duringSceneGui` are fine. The Transition Preview Window actually inherits from `SceneView` and I use those same events for things like the [Platformer Game Kit's Hit Boxes](https://kybernetik.com.au/platformer/docs/combat/melee/#drawer).

I think I've found a solution though: you can just make scripts which inherit from the regular IK scripts and give them the necessary attribute:

```
[ExecuteInEditMode]
public class IKManager2DWithEditMode : IKManager2D { }
```
And:
```
[ExecuteInEditMode]
public class LimbSolver2DWithEditMode : LimbSolver2D
{
    [CustomEditor(typeof(LimbSolver2DWithEditMode))]
    public class Editor : UnityEditor.U2D.IK.LimbSolver2DEditor { }
}
```
Then you just need to put those on your character instead of the regular ones and the IK seems to work fine in the preview window (and don't forget you need to select the preview's IK target if you want to move it via the settings tab instead of the one in the regular scene Hierarchy).

**Comment by superkerokero** [comment]
Thanks for sharing the workaround.

Tested it and it does make the IK work as well. But it seems that the Gizmos still don't update. Gizmos seem to be updated inside IKEditorManager, which happens to be an internal class...

I still don't fully understand why adding [ExecuteInEditMode] works, but commenting `DisableUnnecessaryComponents` doesn't work though. If the SceneView callbacks are triggered properly in the preview window, commenting `DisableUnnecessaryComponents` should be enough? And the Gizmos should be working too...

**Comment by KybernetikGames** [comment]
The gizmos look like they're working to me, but I haven't used the system before so I could be wrong. What do they look like for you?

**Comment by KybernetikGames** [comment]
Actually, I was just looking at the gizmos visually but if you're referring to input on the gizmos not working, it would be caused by this code in `TransitionPreviewWindow.OnSceneGUI`:

```
            // Don't allow clicks in this window to select objects in the preview scene.
            if (activeObject != Selection.activeObject)
                DeselectPreviewSceneObjects();
```
If you comment that out, clicking on the IK gizmos seems to do what I'd expect.

I wanted to prevent you from easily selecting preview objects and modifying them then wondering why your changes were lost when you close the window, but maybe I'll just allow it and try to find another way to make it obvious that you're in preview mode.

**Comment by superkerokero** [comment]
The gizmos I'm referring to are these green dots and dashed lines. They should follow the bones related to the IK solver. In this case, these dots should align with the arm as the IK target moves.

This is what it looks like in preview window:
![image](https://user-images.githubusercontent.com/8372499/150339760-61785b3d-8029-4901-94db-a13497dc68c7.png)

This is what it looks like in default scene view:
![image](https://user-images.githubusercontent.com/8372499/150340287-1b5d4f5f-627c-46f4-a96a-a4425196c309.png)

By the way, I am using M1 macbook along with the Apple silicon version of Unity 2021.2.8f1, maybe it's system specific?

**Comment by KybernetikGames** [comment]
Didn't see those, yeah, they're not working properly for me either. The green dots for the scene view character show in the preview window so you're actually controlling the character in the scene which you can't currently see. And the preview character doesn't seem to show their ones at all.

The gizmos I was talking about are these white ones:
![image](https://user-images.githubusercontent.com/43698611/150341189-8bf27520-e3f1-4e98-8482-85ef65d3d3bb.png)
But those looks like they're directly controlling all the character's bones, not the IK.

**Comment by superkerokero** [comment]
> The green dots for the scene view character show in the preview window so you're actually controlling the character in the scene which you can't currently see.

OK, this makes sense now.

Yes the bones are drawn from sprite skins and they work well for me too.

**Comment by KybernetikGames** [comment]
[Animancer v7.3](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-3/) is now available and has this fix in it.
