### ISSUE TITLE
SpriteRendererTextureSwaper sets the sprite to "None"

### ISSUE THREAD

**Issue by LazyEti** [KybernetikGames/animancer#444]
# Environment

- Animancer Version Number: 8.2.3
- Animancer Pro or Lite: lite
- Unity Version: 6.0.59
- Platform: Windows

# Description
I'm trying to use the SpriteRendererTextureSwaper component to swap the player's skin at runtime but Changing the texture via "SpriteRendererTextureSwaper.Texture = texture;"  is inconsistent and sometimes sets the sprite to none (making the character disappear entirely).

I tried to add a delay and re-enable the component to force refresh like so:

`      spriteSwaper.enabled = false;
      spriteSwaper.Texture = spriteSwaps[colorIndex];
      DOVirtual.DelayedCall (.1f, () => spriteSwaper.enabled = true);`

It seems to do the trick most of the time but there is some rare cases where it still overrides the sprite to none.

# Reproduction

My setup:
1. having a regular animator with simple clips that I trigger via animator.play()
2. having multiple sprite sheets variation that you want to swap
3. use SpriteRendererTextureSwaper.Texture = someReplacementSheetTex; to swap the texture

**Comment by LazyEti** [comment]
heya @KybernetikGames thanks for getting back so quick!
I looked into it and the issue was due to the sprite being set to null at line 230 because "otherSprite" was not set.
It seems to be due to the fact that changing the texture through code instead of in editor doesn't trigger "OnValidate" and never destroys or refresh the _SpriteMap dictionary.

i didn't take the time to read the whole script so I fixed the issue by quickly adding a public function:
 
```
public void ChangeTexture(Texture2D tex)
        {
            _Texture = tex;
            if (_SpriteMap != null) DestroySprites (_SpriteMap);
        }
```

This works but i would suggest that you add an automatic check to see if the texture has been changed or even a Dictionary of dictionary (Dictionary<Texture, Dictionary<Sprite, Sprite>>) so multiple maps can be cached and handled.

**Comment by KybernetikGames** [comment]
That should already be handled by the `Texture` property though:

```
        public Texture2D Texture
        {
            get => _Texture;
            set
            {
                _Texture = value;
                RefreshSpriteMap();
            }
        }
```

Am I missing something here? It looks like that property should achieve the same thing as your method and your original code snippet looks like you were using it. Even then, I'm never seeing the sprite get set to null if I directly set the `_Texture` either.

How is it getting to the line `sprite = otherSprite;` with `otherSprite` being `null`?

The only way I can see that happening is if it wasn't yet in the dictionary and `Sprite.Create` returns `null`:

<img width="595" height="398" alt="Image" src="https://github.com/user-attachments/assets/610af41b-f0b0-441f-a5ca-d54ba0570788" />

But I'm not aware of any circumstances where `Sprite.Create` would return `null` and if it did, then it would cause a `NullReferenceException` further down where it sets the `otherSprite.name`:

<img width="412" height="123" alt="Image" src="https://github.com/user-attachments/assets/b85ba3b7-6cd9-4db3-a277-f6c13131dbf9" />

**Comment by LazyEti** [comment]
I don't know why but I think the problem might have been related to changing the texture and then playing a new animation. Somehow the SpriteMap dictionary kept all the keys but swapped all the values to null.

So the IF statement  (!spriteMap.TryGetValue(sprite, out var otherSprite)) would return true because the value exists and thus the "otherSprite" is just created as a null and the code where otherSprite = Sprite.Create never runs

**Comment by KybernetikGames** [comment]
A simpler fix would be to change `TrySwapTexture` to do:

```
            if (!spriteMap.TryGetValue(sprite, out var otherSprite) ||
                otherSprite == null)
```

But I still can't see any way for the dictionary values to be null. Nothing is explicitly setting them after they get added on creation and the only place anything is destroyed is in `DestroySprites` which completely clears the dictionary right afterwards. Are you perhaps destroying the sprite somewhere in your own scripts?

**Comment by LazyEti** [comment]
> A simpler fix would be to change `TrySwapTexture` to do:
> 
> ```
>             if (!spriteMap.TryGetValue(sprite, out var otherSprite) ||
>                 otherSprite == null)
> ```
 
ok this works too but needs a check at the end like so:
```
                if (spriteMap.ContainsKey (sprite)) spriteMap [sprite] = otherSprite;
                else  spriteMap.Add (sprite, otherSprite);
```

I have no idea why it's happening as I mentioned. I'm not touching the sprite renderer component in any way other than setting a material property block. The only other thing affecting it is the default unity animator being trigger with animator.Play("animation");

Perhaps it has something to do with odin, hotreload or some other thing in my project? unfortunately I can't share a sample project

**Comment by KybernetikGames** [comment]
> ok this works too but needs a check at the end like so:

You can just do `spriteMap[sprite] = otherSprite;` to avoid needing to check `ContainsKey`.

> odin

Odin is great at randomly breaking things, but in this case it seems unlikely to be related, particularly if it's happening when you don't have anything selected so Odin isn't doing anything in the Inspector.

> hotreload

I haven't used HotReload, but it sounds more plausible since it could be causing Unity to destroy the old sprites during a reload. Are you able to easily disable it to see if the issue still occurs? Does it only occur after causing a reload?
